### ISSUE TITLE
Choose models

### ISSUE THREAD

**Issue by jaimedantas** [EECS-4404/dataset#5]
Three classification models need to be selected. The possible models are:
- Feed-forward Neural network
- Random forest
- K-nearest neighbour predictor
- Kernelized support vector machine

**Comment by vivianyu885** [comment]
The majority of the group members (6/9) agreed to work with ["Electrical Grid Stability Simulated Data Data Set"](http://archive.ics.uci.edu/ml/datasets/Electrical+Grid+Stability+Simulated+Data+).

**Comment by jaimedantas** [comment]
The choices are:
- Fee-forward Neural network
- K-nearest neighbour predictor
- Kernelized support vector machine
